language: rust
rust:
- stable
sudo: false
env:
  global:
    - secure: LJMKj7cTy7nl4xBsjkjDuo3JCXUMO/HsO5iAqJM1r/bFaAQCM4Ef9GT10wEXE5UL54owRc0P1mt4RJ/QziZD9xCA9qSV4tQFIbAjPHHM9ANmffwr+z9p12LZByzE8r2lFX1UqLCUGxnQ6Hd9wokMInp/mRmB13U1fVqPVINY4wkVxQjoLXqUZ3d1jV2O4CITdXKO0rX5uHYkGKeS3Ft+Uz8UJgD/uuzP0B4nP4vRPaRXBfiJp9aSCG3mYfzzgVZIuceC1a64NqoYGpMhD8Ptod9Yqudcp7FCqpQyDAFmXKN3PDmhZvcLiVHI1ojpTKqoBWprnqAx9ppCJIV1YsNMueFLb4JARXt+vx5LN8KJcLzCn8J8/VDsun14k4eRxea4+K6Cef99roSu8PXQkYSQm/kMgc6POUz9SVlYipMBFlihV51QKk7JSswiHmJVfr3DVdmD+lx1NtSN4Oj8UpplZy1CKRDlZRrOJkBUM9VaZoLju4fsLY+PAITVldmaVkJC4C20+8g6A90MBp1c2RVlayTkoe08FWXU/s6RugrZq0np1hQOeURp02oPnTTpEd7GqZLifhDgqzjuY/drsTG7M7xCT9bri7MzDXNvJGuNllYRF7FN4gl/j7KN0dQ+IJtN4we52tuufv/HxY1LD7/lc7QBWUtn4Nm2QVNXjLliStk=
